name: Create PR

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout src repo
        uses: actions/checkout@v3
        with:
          path: temp-src-repo

      - name: Checkout dst repo
        uses: actions/checkout@v3
        with:
          repository: ciur/dst-repo
          path: temp-dst-repo

      - name: Generate File
        run: |
          cd temp-src-repo
          chmod +x ./generate.sh
          ./generate.sh > ../temp-dst-repo/date.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_PAT_TOKEN }}
          add-paths: |
            date.txt
          path: temp-dst-repo
          labels: automerge

      - name: Automerge
        id: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
            GITHUB_TOKEN: "${{ secrets.GH_PAT_TOKEN }}"
