name: Create PR

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout src repo
        uses: actions/checkout@v3
        with:
          path: temp-src-repo

      - name: Checkout dst repo
        uses: actions/checkout@v3
        with:
          repository: ciur/dst-repo
          path: temp-dst-repo

      - name: Generate File
        run: |
          cd temp-src-repo
          chmod +x ./generate.sh
          ./generate.sh > ../temp-dst-repo/date.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_PAT_TOKEN }}
          add-paths: |
            date.txt
          path: temp-dst-repo

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GH_PAT_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
          repository: ciur/dst-repo
