name: Dispatch

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GH_PAT_TOKEN:
        required: true

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger dispatch event for 3rd repo
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'ciur',
              repo: '3rd-repo',
              workflow_id: 'generate.yml',
              ref: 'main'
            })