name: Update OpenAPI Schema

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GH_PAT_TOKEN:
        required: true

jobs:
  update-openapi-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Clone src repo
        uses: actions/checkout@master
        with:
          repository: ciur/src-repo
          path: temp-src-repo
          ref: master

      - name: Checkout dst repo
        uses: actions/checkout@master
        with:
          repository: ciur/dst-repo
          path: temp-dst-repo

      - name: Generate File
        run: |
          cat temp-src-repo/version.py
          cat temp-src-repo/version.py > temp-dst-repo/date.txt

      - name: Echo created file
        run: |
            cat temp-dst-repo/date.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          token: ${{ secrets.GH_PAT_TOKEN }}
          add-paths: |
            date.txt
          path: temp-dst-repo
          labels: automerge

      - name: Merge
        uses: KeisukeYamashita/auto-pull-request-merge@v1
        with:
          intervalSeconds: 10
          timeoutSeconds: 60
          labels: automerge
          repository: ciur/dst-repo
          pullRequestNumber:  ${{ steps.cpr.outputs.pull-request-number }}
          token: ${{ secrets.GH_PAT_TOKEN }}
          checkStatus: false

  job:
    # https://github.com/orgs/community/discussions/26323
    dispatch:
      needs: [update-openapi-schema]
      runs-on: ubuntu-latest
      steps:
      - name:
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'ciur',
              repo: '3rd-repo',
              workflow_id: 'generate.yml',
              ref: 'main'
            })