name: Version Bump

on:
  workflow_dispatch:

jobs:
  version-bump:
    runs-on: ubuntu-latest
    outputs:
      old-version: ${{ steps.step-version-bump.outputs.OLD_VERSION }}
      new-version: ${{ steps.step-version-bump.outputs.NEW_VERSION }}
    steps:
      - uses: actions/checkout@master

      - name: Version bump
        id: step-version-bump
        uses: papermerge/banger@master
        with:
          files_list: "version.py"

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "version bump ${{steps.step-version-bump.outputs.OLD_VERSION}} -> ${{steps.step-version-bump.outputs.NEW_VERSION}}" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
  update-openapi-schema:
    runs-on: ubuntu-latest
    needs:
      - version-bump
    steps:
      - name: Checkout src repo
        uses: actions/checkout@v3
        with:
          path: temp-src-repo

      - name: Checkout dst repo
        uses: actions/checkout@v3
        with:
          repository: ciur/dst-repo
          path: temp-dst-repo

      - name: Generate File
        run: |
          cd temp-src-repo
          chmod +x ./generate.sh
          ./generate.sh > ../temp-dst-repo/date.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_PAT_TOKEN }}
          add-paths: |
            date.txt
          path: temp-dst-repo
          labels: automerge

      - name: Merge
        uses: KeisukeYamashita/auto-pull-request-merge@v1
        with:
          intervalSeconds: 10
          timeoutSeconds: 30
          labels: automerge
          repository: ciur/dst-repo
          pullRequestNumber:  ${{ steps.cpr.outputs.pull-request-number }}
          token: ${{ secrets.GH_PAT_TOKEN }}
          checkStatus: false
